# Generated by Django 5.1.6 on 2025-02-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_healthdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='blood_sugar',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='recorded_at',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
