# Generated by Django 5.1.6 on 2025-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_patient_remove_healthrecord_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(default='120/80', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='patient',
            name='pulse_rate',
            field=models.IntegerField(default=72),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
