# Generated by Django 5.1.7 on 2025-03-25 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_remove_patient_created_at_patient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckupCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='bp',
            new_name='pulse_rate',
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='timestamp',
            new_name='recorded_at',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='blood_pressure',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='blood_pressure',
            field=models.CharField(default=80, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='pulse',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.patient'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
    ]
